# Generated by Django 5.2.5 on 2025-08-11 17:58

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    def create_super_user(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        if User.objects.exclude():
            return

        superuser = User.objects.create_superuser(
            username="cheikh",
            email="cheikh@gmail.com",
            password="root",
            last_login=timezone.now(),
            first_name="Cheikh",
            last_name="El Bidhany",
            role="cheikh"
        )

        superuser = User.objects.create_superuser(
            username="tlmi4",
            email="tlmi4@gmail.com",
            password="root",
            last_login=timezone.now(),
            first_name="TLM",
            last_name="I4",
            role="student"
        )

        superuser.save()

    operations = [
        migrations.RunPython(create_super_user)
    ]