# Generated by Django 5.2.5 on 2025-08-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_super_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('cheikh', 'Cheikh'), ('etudiant', 'Étudiant')], default='etudiant', max_length=10),
        ),
    ]
