# Generated by Django 5.2.5 on 2025-08-11 17:58

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    def create_super_user(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()

        if User.objects.exclude():
            return

        superuser = User.objects.create_superuser(
            username="medsidatt",
            email="mdaloueimin@gmail.com",
            password="root",
            role="admin",
            last_login=timezone.now()
        )

        superuser.save()

    operations = [
        migrations.RunPython(create_super_user)
    ]